#!/usr/bin/env bash

# Copyright 2019 Edward G. Bruck <ed.bruck1@gmail.com>
#
# This file is part of Radiotray-NG.
#
# Radiotray-NG is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: rtng-dbus <command> [ARG1] [ARG2]

Commands:
  get_bookmarks
  get_config
  get_player_state
  mute
  next_station
  play
  play_station <group> <station>
  play_url <url>
  previous_station
  quit
  reload_bookmarks
  set_volume <level>
  stop
  volume_down
  volume_up
USAGE
}

if (($# == 0)); then
    usage
    exit 1
fi

command_name="$1"
shift

case "$command_name" in
    get_bookmarks|get_config|get_player_state|mute|next_station|play|play_station|play_url|previous_station|quit|reload_bookmarks|set_volume|stop|volume_down|volume_up)
        ;;
    *)
        printf 'Unknown RadioTray-NG D-Bus command: %s\n' "$command_name" >&2
        usage >&2
        exit 2
        ;;
esac

# RadioTray-NG lives on the login session bus. Creating a new private bus
# would not contain the already-running RadioTray-NG service.
if [[ -z ${DBUS_SESSION_BUS_ADDRESS:-} ]]; then
    runtime_bus="/run/user/$(id -u)/bus"
    if [[ -S "$runtime_bus" ]]; then
        export DBUS_SESSION_BUS_ADDRESS="unix:path=${runtime_bus}"
    else
        printf 'RadioTray-NG session bus not found at %s.\n' "$runtime_bus" >&2
        exit 3
    fi
fi

args=()
for arg in "$@"; do
    args+=("string:${arg}")
done

dbus-send \
    --session \
    --print-reply=literal \
    --type=method_call \
    --dest=com.github.radiotray_ng \
    /com/github/radiotray_ng \
    "com.github.radiotray_ng.${command_name}" \
    "${args[@]}"
